print("Let's play a game...")
print("Enter a place you hate here:")
place = input()
print("Enter a friend name here:")
name =  input()
print("Enter a abstract noun here:")
abstract = input()
print("Enter a name of a famous person here:")
name_of_a_famous_person = input()
print("Enter a number here:")
number = input()
print("Enter age of friend here:")
age = input()
print("Enter another number here:")
another_number = input()
print("A former " + place + " police officer " + name + " was sentenced Thursday to spend the rest of his life in prison after his conviction for raping and sexually abusing women in a low-income neighborhood while on the " + abstract + ".")
print("District Judge " + name_of_a_famous_person + " agreed with an earlier court recommendation and sentenced Daniel Holtzclaw to " + number + " years in prison for the attacks on black women in a low-income neighborhood between 2013 and 2014. Holtclaw, " + age + ", had been charged with " + another_number + " counts.")
